export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>ANGULARFORMROLEANDEMPLOYEE</title>
  <base href="/AngularFormRoleandEmployee/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["input","compositionstart","compositionend","change","click"],["blur"]);</script>
  <!-- <app-root></app-root> -->
 <app-employee-component ng-version="19.2.14" ngh="0" ng-server-context="ssg"><p>Enter Name:</p><input type="text" name="employeename" placeholder="Enter your Name" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><p>Enter E-Mail:</p><input type="email" name="employeeEmail" placeholder="Enter your E-Mail" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><p>Password</p><input type="password" name="employeePassword" placeholder="Enter your Password" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div class="section"><h3 style="font-weight: bold;">Select a Role</h3><select class="ng-untouched ng-pristine ng-valid" jsaction="change:;blur:;"><option value disabled selected>Select</option><option value="1"> Software Developer </option><option value="2"> Devops Engineer </option><option value="3"> Data Analyst </option><option value="4"> DBA </option><option value="5"> Tester </option><option value="6"> QA </option><!----></select></div><div><button id="btn" type="button" title="Save" jsaction="click:;"> 💾 Save </button></div></app-employee-component>
<script src="polyfills-B6TNHZQ6.js" type="module"></script><script src="main-4GPTU2WG.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"15":"t0"},"c":{"15":[{"i":"t0","r":1,"x":6}]}}]}</script></body></html>`;